/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Computacion
 */
public class Cajero extends javax.swing.JFrame {

    /**
     * Creates new form Cajero
     */
    public Cajero() {
      initComponents();

    getContentPane().setBackground(new java.awt.Color(255, 255, 255));

    setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    setLocationRelativeTo(null);

    cargarImagenCajera();
    cargarIconoCarnet();
   
    }
    
    private void cargarIconoCarnet() {

    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource("/Imagenes/icar.png")
    );

    java.awt.Image imagen = icon.getImage();

    // Tamaño que queremos para el icono
    int ancho = 35;
    int alto = 35;

    java.awt.Image imagenEscalada = imagen.getScaledInstance(
            ancho,
            alto,
            java.awt.Image.SCALE_SMOOTH
    );

    lblIconoCarnet.setIcon(
            new javax.swing.ImageIcon(imagenEscalada)
    );

    lblIconoCarnet.setText("");
    lblIconoCarnet.setHorizontalAlignment(
            javax.swing.SwingConstants.CENTER
    );
}
private void cargarImagenCajera() {

    javax.swing.ImageIcon icon = new javax.swing.ImageIcon(
            getClass().getResource("/Imagenes/cajer.png")
    );

    int anchoLabel = lblCajera.getWidth();
    int altoLabel = lblCajera.getHeight();

    int anchoImagen = icon.getIconWidth();
    int altoImagen = icon.getIconHeight();

    double escala = Math.min(
            (double) anchoLabel / anchoImagen,
            (double) altoLabel / altoImagen
    );

    int nuevoAncho = (int) (anchoImagen * escala);
    int nuevoAlto = (int) (altoImagen * escala);

    java.awt.Image imagenEscalada = icon.getImage().getScaledInstance(
            nuevoAncho,
            nuevoAlto,
            java.awt.Image.SCALE_SMOOTH
    );

    lblCajera.setIcon(new javax.swing.ImageIcon(imagenEscalada));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        panelPrincipal = new javax.swing.JPanel();
        lblCajera = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        lblIconoInfo = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        panelInfo = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        lblIconoCarnet = new javax.swing.JLabel();
        btnEscanear = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Identificación del Cajero");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setToolTipText("");
        panelPrincipal.setLayout(null);

        lblCajera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrincipal.add(lblCajera);
        lblCajera.setBounds(410, 190, 510, 570);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 0));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("<html>IDENTIFICACIÓN <font color=\"#D92318\">DEL CAJERO</font></html> ");
        panelPrincipal.add(lblTitulo);
        lblTitulo.setBounds(1490, 100, 420, 130);

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(150, 150, 150));
        lblSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubtitulo.setText("Escanea o ingresa el número de carnet ");
        panelPrincipal.add(lblSubtitulo);
        lblSubtitulo.setBounds(1520, 210, 380, 90);

        lblIconoInfo.setBackground(new java.awt.Color(255, 190, 25));
        lblIconoInfo.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        lblIconoInfo.setForeground(new java.awt.Color(255, 190, 25));
        lblIconoInfo.setText("●");
        panelPrincipal.add(lblIconoInfo);
        lblIconoInfo.setBounds(1540, 250, 30, 110);

        lblInfo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(90, 90, 90));
        lblInfo.setText("<html> Acerca tu carnet al lector para escanearlo<br> o ingresa el número manualmente. </html>");
        panelPrincipal.add(lblInfo);
        lblInfo.setBounds(1590, 260, 350, 100);

        panelInfo.setBackground(new java.awt.Color(254, 248, 233));
        panelInfo.setForeground(new java.awt.Color(0, 0, 0));
        panelInfo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        panelInfo.setOpaque(true);
        panelPrincipal.add(panelInfo);
        panelInfo.setBounds(1520, 280, 390, 70);

        txtCarnet.setBackground(new java.awt.Color(255, 255, 255));
        txtCarnet.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtCarnet.setForeground(new java.awt.Color(145, 145, 145));
        txtCarnet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCarnet.setText("N° de carnet... ");
        txtCarnet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 100, 100), 1, true));
        txtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnetActionPerformed(evt);
            }
        });
        panelPrincipal.add(txtCarnet);
        txtCarnet.setBounds(1540, 410, 370, 50);

        lblIconoCarnet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelPrincipal.add(lblIconoCarnet);
        lblIconoCarnet.setBounds(1430, 400, 110, 70);

        btnEscanear.setBackground(new java.awt.Color(210, 32, 22));
        btnEscanear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEscanear.setForeground(new java.awt.Color(225, 225, 225));
        btnEscanear.setText("ESCANEAR CARNET");
        btnEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscanearActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnEscanear);
        btnEscanear.setBounds(1530, 480, 390, 48);

        getContentPane().add(panelPrincipal);
        panelPrincipal.setBounds(-290, 0, 3628, 1129);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnetActionPerformed

    private void btnEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscanearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscanearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscanear;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCajera;
    private javax.swing.JLabel lblIconoCarnet;
    private javax.swing.JLabel lblIconoInfo;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel panelInfo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtCarnet;
    // End of variables declaration//GEN-END:variables
}
