
package GUI;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        this.setExtendedState(Login.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEscalable4 = new Labels.LabelEscalable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEscalable7 = new Labels.LabelEscalable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelEscalable6 = new Labels.LabelEscalable();
        botonAzul3 = new Componentes.BotonAzul();
        botonRojo1 = new Componentes.BotonRojo();
        labelEscalable1 = new Labels.LabelEscalable();
        labelEscalable5 = new Labels.LabelEscalable();
        labelEscalable3 = new Labels.LabelEscalable();
        labelEscalable2 = new Labels.LabelEscalable();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelEscalable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ojo.png"))); // NOI18N
        labelEscalable4.setText("labelEscalable1");
        getContentPane().add(labelEscalable4);
        labelEscalable4.setBounds(-5, 0, 910, 1010);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Speedee", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WcDonal´s");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(840, 250, 280, 100);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Administrador");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(450, 620, 280, 49);

        labelEscalable7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wc (3).png"))); // NOI18N
        jPanel1.add(labelEscalable7);
        labelEscalable7.setBounds(470, 462, 180, 150);

        jLabel3.setFont(new java.awt.Font("Speedee", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bienvenido a ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(520, 270, 370, 62);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("futuro!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(980, 710, 80, 22);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("Cajero");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(950, 620, 120, 49);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Identificacion y acceso para el");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(870, 680, 270, 22);

        labelEscalable6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wc (1).png"))); // NOI18N
        jPanel1.add(labelEscalable6);
        labelEscalable6.setBounds(920, 430, 180, 180);

        botonAzul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAzul3ActionPerformed(evt);
            }
        });
        jPanel1.add(botonAzul3);
        botonAzul3.setBounds(405, 793, 330, 80);

        botonRojo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRojo1ActionPerformed(evt);
            }
        });
        jPanel1.add(botonRojo1);
        botonRojo1.setBounds(842, 793, 330, 80);

        labelEscalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componentes/Wc (3).png"))); // NOI18N
        jPanel1.add(labelEscalable1);
        labelEscalable1.setBounds(360, 400, 420, 500);

        labelEscalable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Componentes/Wc (4).png"))); // NOI18N
        jPanel1.add(labelEscalable5);
        labelEscalable5.setBounds(800, 400, 410, 500);

        labelEscalable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gemini_Generated_Image_nev4cjnev4cjnev4 (1).png"))); // NOI18N
        labelEscalable3.setText("labelEscalable3");
        jPanel1.add(labelEscalable3);
        labelEscalable3.setBounds(460, -60, 690, 400);
        jPanel1.add(labelEscalable2);
        labelEscalable2.setBounds(620, 730, 0, 0);

        jLabel4.setFont(new java.awt.Font("Speedee", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bienvenido a ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(490, 290, 370, 62);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Acceso completo para ti!");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 680, 250, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(610, -10, 1350, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAzul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAzul3ActionPerformed

        Administrador nuevo = new Administrador();
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAzul3ActionPerformed

    private void botonRojo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRojo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRojo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonAzul botonAzul3;
    private Componentes.BotonRojo botonRojo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private Labels.LabelEscalable labelEscalable1;
    private Labels.LabelEscalable labelEscalable2;
    private Labels.LabelEscalable labelEscalable3;
    private Labels.LabelEscalable labelEscalable4;
    private Labels.LabelEscalable labelEscalable5;
    private Labels.LabelEscalable labelEscalable6;
    private Labels.LabelEscalable labelEscalable7;
    // End of variables declaration//GEN-END:variables
}
