
package MenuCajero;

import java.awt.CardLayout;

public class Cajero extends javax.swing.JFrame {

    private CardLayout cardLayout;

    public Cajero() {
        initComponents();
        this.setExtendedState(Cajero.MAXIMIZED_BOTH);
        
        cardLayout = (CardLayout) panelCentro.getLayout();
        panelCentro.add(new WcMenu(), "PANEL_MENU");

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        labelEscalable1 = new Labels.LabelEscalable();
        SubPanelCabecera = new javax.swing.JPanel();
        botonAdmi1 = new Componentes.BotonAdmi();
        botonAdmi2 = new Componentes.BotonAdmi();
        panelPerfil1 = new javax.swing.JPanel();
        PanelLado = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cabecera.setBackground(new java.awt.Color(255, 255, 255));
        cabecera.setMaximumSize(new java.awt.Dimension(10, 10));
        cabecera.setPreferredSize(new java.awt.Dimension(0, 100));
        cabecera.setLayout(new java.awt.BorderLayout());

        labelEscalable1.setBackground(new java.awt.Color(219, 219, 219));
        labelEscalable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        labelEscalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wc (6).png"))); // NOI18N
        labelEscalable1.setPreferredSize(new java.awt.Dimension(375, 80));
        cabecera.add(labelEscalable1, java.awt.BorderLayout.WEST);

        SubPanelCabecera.setBackground(new java.awt.Color(255, 255, 255));
        SubPanelCabecera.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        SubPanelCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 58));

        botonAdmi1.setBackground(new java.awt.Color(0, 0, 0));
        botonAdmi1.setForeground(new java.awt.Color(0, 0, 0));
        botonAdmi1.setText("Wc Menu");
        botonAdmi1.setInactiveTextColor(new java.awt.Color(0, 0, 0));
        botonAdmi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdmi1ActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(botonAdmi1);

        botonAdmi2.setText("Ordenes");
        SubPanelCabecera.add(botonAdmi2);

        cabecera.add(SubPanelCabecera, java.awt.BorderLayout.CENTER);

        panelPerfil1.setBackground(new java.awt.Color(204, 204, 204));
        panelPerfil1.setPreferredSize(new java.awt.Dimension(300, 100));
        panelPerfil1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        cabecera.add(panelPerfil1, java.awt.BorderLayout.EAST);

        getContentPane().add(cabecera, java.awt.BorderLayout.NORTH);

        PanelLado.setBackground(new java.awt.Color(255, 255, 255));
        PanelLado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        PanelLado.setPreferredSize(new java.awt.Dimension(375, 0));
        PanelLado.setLayout(null);
        getContentPane().add(PanelLado, java.awt.BorderLayout.WEST);

        panelCentro.setBackground(new java.awt.Color(255, 255, 255));
        panelCentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        panelCentro.setPreferredSize(new java.awt.Dimension(20, 20));
        panelCentro.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAdmi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdmi1ActionPerformed
        cardLayout.show(panelCentro, "PANEL_MENU");

        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdmi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLado;
    private javax.swing.JPanel SubPanelCabecera;
    private Componentes.BotonAdmi botonAdmi1;
    private Componentes.BotonAdmi botonAdmi2;
    private javax.swing.JPanel cabecera;
    private Labels.LabelEscalable labelEscalable1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelPerfil1;
    // End of variables declaration//GEN-END:variables
}
