
package MenuCajero;

import Modelo.MoldeProductos;
import java.awt.CardLayout;
import java.awt.Component;


public class WcMenu extends javax.swing.JPanel {

    private CardLayout cardLayout;

    public WcMenu() {
        initComponents();
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setOpaque(false);
        
        jScrollPane2.getViewport().setOpaque(false);
        jScrollPane2.setOpaque(false);
        
        jScrollPane3.getViewport().setOpaque(false);
        jScrollPane3.setOpaque(false);
    panelGrid.setOpaque(false);
    
    // 1. MARCAR EL BOTÓN DE HAMBURGUESAS COMO SELECCIONADO (AMARILLO)
    botonCategoria1.setSelected(true);
    
    // 2. CARGAR LOS PRODUCTOS DE LA CATEGORÍA 1 (HAMBURGUESAS)
    cargarProductosPorCategoria(1);

    
        
    }
    
    public void buscarProductos(String textoBusqueda) {
    if (textoBusqueda == null || textoBusqueda.trim().isEmpty()) {
        // Si el buscador está vacío, vuelve a la categoría 1 por defecto
        cargarProductosPorCategoria(1);
        return;
    }

    panelGrid.removeAll();
    panelGrid.setLayout(new java.awt.GridLayout(0, 3, 15, 15));

    Conexion.ProductoDAO dao = new Conexion.ProductoDAO();
    java.util.List<Modelo.Producto> lista = dao.buscarProductosPorNombre(textoBusqueda);

    for (Modelo.Producto p : lista) {
        Modelo.MoldeProductos tarjeta = new Modelo.MoldeProductos();
        tarjeta.setDatos(p);

        tarjeta.getBtnAgregar().addActionListener(e -> {
            agregarProductoAOrden(p);
        });

        panelGrid.add(tarjeta);
    }

    javax.swing.JPanel panelContenedor = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelContenedor.setOpaque(false);
    panelContenedor.add(panelGrid, java.awt.BorderLayout.NORTH);

    jScrollPane3.setViewportView(panelContenedor);

    panelGrid.revalidate();
    panelGrid.repaint();
}
    
public void cargarProductosPorCategoria(int idCategoria) {
    panelGrid.removeAll();
    // 3 columnas fijas con espacio de 15px entre elementos
    panelGrid.setLayout(new java.awt.GridLayout(0, 3, 15, 15));

    Conexion.ProductoDAO dao = new Conexion.ProductoDAO();
    java.util.List<Modelo.Producto> lista = dao.obtenerProductosPorCategoria(idCategoria);

    for (Modelo.Producto p : lista) {
        if (p.isDisponible()) {
            MoldeProductos tarjeta = new MoldeProductos();
            tarjeta.setDatos(p);

            // --------------------------------------------------------------------
            // LÍNEA CLAVE: Conecta el botón '+' con el panel de la orden (jPanel3)
            // --------------------------------------------------------------------
            tarjeta.getBtnAgregar().addActionListener(e -> {
                agregarProductoAOrden(p);
            });

            panelGrid.add(tarjeta);
        }
    }

    // Contenedor auxiliar alineado al norte (impide la deformación vertical)
    javax.swing.JPanel panelContenedor = new javax.swing.JPanel(new java.awt.BorderLayout());
    panelContenedor.setOpaque(false);
    panelContenedor.add(panelGrid, java.awt.BorderLayout.NORTH);

    jScrollPane3.setViewportView(panelContenedor);

    panelGrid.revalidate();
    panelGrid.repaint();
}

private void agregarProductoAOrden(Modelo.Producto producto) {
    // 1. Convertir la ruta String a java.awt.Image
    java.awt.Image img = null;
    String ruta = producto.getImagenPath();
    if (ruta != null && !ruta.trim().isEmpty()) {
        java.io.File archivo = new java.io.File(ruta.trim());
        if (archivo.exists()) {
            img = new javax.swing.ImageIcon(archivo.getAbsolutePath()).getImage();
        }
    }

    // 2. Pasar la imagen cargada a ItemOrden
    Componentes.ItemOrden item = new Componentes.ItemOrden(
            producto.getNombre(),
            producto.getPrecio(),
            img,
            () -> recalcularSubtotal()
    );

    jPanel3.add(item);
    jPanel3.revalidate();
    jPanel3.repaint();

    recalcularSubtotal();
}

// Recorre los ítems agregados y actualiza la etiqueta del subtotal
private void recalcularSubtotal() {
    double total = 0.0;
    for (Component c : jPanel3.getComponents()) {
        if (c instanceof Componentes.ItemOrden) {
            total += ((Componentes.ItemOrden) c).getSubtotal();
        }
    }
    // Asegúrate de que tu JLabel se llama 'subtotal' o cámbialo por su variable
    subtotal.setText(String.format("Q %.2f", total));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRedondeadoSombra1 = new Componentes.PanelRedondeadoSombra();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelTotalesAcciones = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        subtotal = new javax.swing.JLabel();
        subtotal1 = new javax.swing.JLabel();
        boton1 = new Componentes.boton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        PanelCentral = new javax.swing.JPanel();
        panelRedondeadoSombra2 = new Componentes.PanelRedondeadoSombra();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buscador2 = new Componentes.Buscador();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelBotonesCategorias = new javax.swing.JPanel();
        botonCategoria1 = new Componentes.BotonCategoria();
        botonCategoria5 = new Componentes.BotonCategoria();
        botonCategoria6 = new Componentes.BotonCategoria();
        botonCategoria7 = new Componentes.BotonCategoria();
        PanelComidas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        panelGrid = new javax.swing.JPanel();
        Panelzquierda = new Componentes.PanelRedondeadoSombra();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        panelRedondeadoSombra1.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondeadoSombra1.setPreferredSize(new java.awt.Dimension(400, 100));
        panelRedondeadoSombra1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(18, 18, 1, 1));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("TU ORDEN ");
        jLabel2.setToolTipText("");
        jLabel2.setAlignmentY(5.0F);
        jPanel1.add(jLabel2);

        panelRedondeadoSombra1.add(jPanel1, java.awt.BorderLayout.NORTH);

        panelTotalesAcciones.setBackground(new java.awt.Color(102, 102, 0));
        panelTotalesAcciones.setForeground(new java.awt.Color(255, 255, 255));
        panelTotalesAcciones.setOpaque(false);
        panelTotalesAcciones.setPreferredSize(new java.awt.Dimension(0, 200));
        panelTotalesAcciones.setLayout(new javax.swing.BoxLayout(panelTotalesAcciones, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subtotal.setFont(new java.awt.Font("Arial Black", 0, 27)); // NOI18N
        subtotal.setForeground(new java.awt.Color(173, 8, 15));
        subtotal.setText("Q 0.00");
        jPanel4.add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        subtotal1.setFont(new java.awt.Font("Arial Black", 0, 27)); // NOI18N
        subtotal1.setForeground(new java.awt.Color(0, 0, 0));
        subtotal1.setText("TOTAL");
        jPanel4.add(subtotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel5.add(jPanel4);

        boton1.setText("PAGAR");
        boton1.setFont(new java.awt.Font("Arial Black", 1, 17)); // NOI18N
        boton1.setPreferredSize(new java.awt.Dimension(350, 60));
        jPanel5.add(boton1);

        panelTotalesAcciones.add(jPanel5);

        panelRedondeadoSombra1.add(panelTotalesAcciones, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel3);

        panelRedondeadoSombra1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(panelRedondeadoSombra1, java.awt.BorderLayout.WEST);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        PanelCentral.setBackground(new java.awt.Color(255, 255, 255));
        PanelCentral.setPreferredSize(new java.awt.Dimension(350, 0));
        PanelCentral.setLayout(new java.awt.BorderLayout());

        panelRedondeadoSombra2.setBackground(new java.awt.Color(255, 255, 255));
        panelRedondeadoSombra2.setPreferredSize(new java.awt.Dimension(0, 130));
        panelRedondeadoSombra2.setLayout(new javax.swing.BoxLayout(panelRedondeadoSombra2, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setBackground(new java.awt.Color(255, 102, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 0, 20));
        jPanel7.setOpaque(false);
        jPanel7.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Comida");
        jPanel7.add(jLabel1, java.awt.BorderLayout.CENTER);

        buscador2.setPreferredSize(new java.awt.Dimension(350, 60));
        buscador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscador2ActionPerformed(evt);
            }
        });
        jPanel7.add(buscador2, java.awt.BorderLayout.EAST);

        panelRedondeadoSombra2.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(0, 130));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelBotonesCategorias.setBackground(new java.awt.Color(255, 255, 255));
        panelBotonesCategorias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        panelBotonesCategorias.setOpaque(false);
        panelBotonesCategorias.setPreferredSize(new java.awt.Dimension(100, 120));
        panelBotonesCategorias.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        botonCategoria1.setPreferredSize(new java.awt.Dimension(165, 50));
        botonCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoria1ActionPerformed(evt);
            }
        });
        panelBotonesCategorias.add(botonCategoria1);

        botonCategoria5.setText("Cafe/Bebidas");
        botonCategoria5.setPreferredSize(new java.awt.Dimension(165, 50));
        botonCategoria5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCategoria5ActionPerformed(evt);
            }
        });
        panelBotonesCategorias.add(botonCategoria5);

        botonCategoria6.setPreferredSize(new java.awt.Dimension(165, 50));
        panelBotonesCategorias.add(botonCategoria6);

        botonCategoria7.setPreferredSize(new java.awt.Dimension(165, 50));
        panelBotonesCategorias.add(botonCategoria7);

        jScrollPane2.setViewportView(panelBotonesCategorias);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        panelRedondeadoSombra2.add(jPanel8);

        PanelCentral.add(panelRedondeadoSombra2, java.awt.BorderLayout.NORTH);

        PanelComidas.setBackground(new java.awt.Color(255, 255, 255));
        PanelComidas.setForeground(new java.awt.Color(255, 255, 255));
        PanelComidas.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBorder(null);

        panelGrid.setLayout(new java.awt.GridLayout(15, 3, 0, 15));
        jScrollPane3.setViewportView(panelGrid);

        PanelComidas.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelComidas, java.awt.BorderLayout.CENTER);

        jPanel2.add(PanelCentral, java.awt.BorderLayout.CENTER);

        Panelzquierda.setBackground(new java.awt.Color(255, 255, 255));
        Panelzquierda.setPreferredSize(new java.awt.Dimension(380, 100));
        jPanel2.add(Panelzquierda, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoria1ActionPerformed
        cargarProductosPorCategoria(1); // Muestra Cafe/Bebidas
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCategoria1ActionPerformed

    private void botonCategoria5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCategoria5ActionPerformed

        cargarProductosPorCategoria(2); // Muestra Cafe/Bebidas
// TODO add your handling code here:
    }//GEN-LAST:event_botonCategoria5ActionPerformed

    private void buscador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscador2ActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_buscador2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelComidas;
    private Componentes.PanelRedondeadoSombra Panelzquierda;
    private Componentes.boton boton1;
    private Componentes.BotonCategoria botonCategoria1;
    private Componentes.BotonCategoria botonCategoria5;
    private Componentes.BotonCategoria botonCategoria6;
    private Componentes.BotonCategoria botonCategoria7;
    private Componentes.Buscador buscador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBotonesCategorias;
    private javax.swing.JPanel panelGrid;
    private Componentes.PanelRedondeadoSombra panelRedondeadoSombra1;
    private Componentes.PanelRedondeadoSombra panelRedondeadoSombra2;
    private javax.swing.JPanel panelTotalesAcciones;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel subtotal1;
    // End of variables declaration//GEN-END:variables
}
