
package MenuAdministrador;

import java.awt.CardLayout;

public class Admi extends javax.swing.JFrame {

    private CardLayout cardLayout;

    public Admi() {
        initComponents();
        this.setExtendedState(Admi.MAXIMIZED_BOTH);
        
        cardLayout = (CardLayout) panelCentro.getLayout();
        
        panelCentro.add(new Usuarios(), "PANEL_USUARIOS");
        panelCentro.add(new Productos1(), "PANEL_PRODUCTOS");
        panelCentro.add(new Categorias(), "PANEL_CATEGORIAS");
        panelCentro.add(new Pagos(), "PANEL_PAGOS");
        panelCentro.add(new Ventas(), "PANEL_VENTAS");
        
        cardLayout.show(panelCentro, "PANEL_USUARIOS");
        
        Usuario.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabecera = new javax.swing.JPanel();
        labelEscalable1 = new Labels.LabelEscalable();
        SubPanelCabecera = new javax.swing.JPanel();
        Usuario = new Componentes.BotonAdmi();
        Pagos = new Componentes.BotonAdmi();
        Ventas = new Componentes.BotonAdmi();
        Producto = new Componentes.BotonAdmi();
        botonAdmi3 = new Componentes.BotonAdmi();
        panelPerfil1 = new javax.swing.JPanel();
        panelCentro = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cabecera.setBackground(new java.awt.Color(173, 8, 15));
        cabecera.setMaximumSize(new java.awt.Dimension(10, 10));
        cabecera.setPreferredSize(new java.awt.Dimension(0, 100));
        cabecera.setLayout(new java.awt.BorderLayout());

        labelEscalable1.setBackground(new java.awt.Color(173, 8, 15));
        labelEscalable1.setForeground(new java.awt.Color(173, 8, 15));
        labelEscalable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Wc (7).png"))); // NOI18N
        labelEscalable1.setPreferredSize(new java.awt.Dimension(375, 80));
        cabecera.add(labelEscalable1, java.awt.BorderLayout.WEST);

        SubPanelCabecera.setBackground(new java.awt.Color(173, 8, 15));
        SubPanelCabecera.setForeground(new java.awt.Color(173, 8, 15));
        SubPanelCabecera.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 27));

        Usuario.setText("Usuarios");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(Usuario);

        Pagos.setText("Pagos");
        Pagos.setToolTipText("");
        Pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagosActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(Pagos);

        Ventas.setText("Ventas");
        Ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentasActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(Ventas);

        Producto.setText("Productos");
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(Producto);

        botonAdmi3.setText("Categoria");
        botonAdmi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdmi3ActionPerformed(evt);
            }
        });
        SubPanelCabecera.add(botonAdmi3);

        cabecera.add(SubPanelCabecera, java.awt.BorderLayout.CENTER);

        panelPerfil1.setBackground(new java.awt.Color(173, 8, 15));
        panelPerfil1.setPreferredSize(new java.awt.Dimension(300, 100));
        panelPerfil1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        cabecera.add(panelPerfil1, java.awt.BorderLayout.EAST);

        getContentPane().add(cabecera, java.awt.BorderLayout.NORTH);

        panelCentro.setBackground(new java.awt.Color(255, 255, 255));
        panelCentro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 216, 216), 1, true));
        panelCentro.setPreferredSize(new java.awt.Dimension(20, 20));
        panelCentro.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        cardLayout.show(panelCentro, "PANEL_USUARIOS");
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        cardLayout.show(panelCentro, "PANEL_PRODUCTOS");

        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoActionPerformed

    private void botonAdmi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdmi3ActionPerformed
        cardLayout.show(panelCentro, "PANEL_CATEGORIAS");

        // TODO add your handling code here:
    }//GEN-LAST:event_botonAdmi3ActionPerformed

    private void VentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentasActionPerformed
                cardLayout.show(panelCentro, "PANEL_VENTAS");

        // TODO add your handling code here:
    }//GEN-LAST:event_VentasActionPerformed

    private void PagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagosActionPerformed

         cardLayout.show(panelCentro, "PANEL_PAGOS");

        // TODO add your handling code here:
    }//GEN-LAST:event_PagosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Componentes.BotonAdmi Pagos;
    private Componentes.BotonAdmi Producto;
    private javax.swing.JPanel SubPanelCabecera;
    private Componentes.BotonAdmi Usuario;
    private Componentes.BotonAdmi Ventas;
    private Componentes.BotonAdmi botonAdmi3;
    private javax.swing.JPanel cabecera;
    private Labels.LabelEscalable labelEscalable1;
    private javax.swing.JPanel panelCentro;
    private javax.swing.JPanel panelPerfil1;
    // End of variables declaration//GEN-END:variables
}
